export const MOVE_CELL_UP = "MOVE_CELL_UP";
export const MOVE_CELL_DOWN = "MOVE_CELL_DOWN";
export const DELETE_CELL = "DELETE_CELL";
export const ADD_CELL = "ADD_CELL";
export const UPDATE_CELL = "UPDATE_CELL";
export const SET_CELL_TITLE = "SET_CELL_TITLE";

export const SELECT_CELL = "SELECT_CELL";
export const MOVE_ROW_UP = "MOVE_ROW_UP";
export const MOVE_ROW_DOWN = "MOVE_ROW_DOWN";
export const DELETE_ROW = "DELETE_ROW";
export const ADD_ROW = "ADD_ROW";
export const UPDATE_ROW = "UPDATE_ROW";

export const SET_SHEET_SUCCESS = "SET_SHEET_SUCCESS";
export const SET_SHEET_FAILED = "SET_SHEET_FAILED";

export const UPDATE_SHEET_SUCCESS = "UPDATE_SHEET_SUCCESS";
export const UPDATE_SHEET_FAILED = "UPDATE_SHEET_FAILED";

export const DELETE_SHEET_SUCCESS = "DELETE_SHEET_SUCCESS";
export const DELETE_SHEET_FAILED = "DELETE_SHEET_FAILED";
